### ISSUE TITLE
转换Rxjava后是否还需要手动Dispose?

### ISSUE THREAD

**Issue by scsfwgy** [YvesCheung/LiveDataToRxJava#5]
Hi,我看你的写法转换后还需要手动Dispose?

`private class LiveDataObservable<T>(
        private val liveData: LiveData<T>,
        private val valueIfNull: T? = null
) : Observable<T>() {

    override fun subscribeActual(observer: io.reactivex.Observer<in T>) {
        if (!checkMainThread(observer)) {
            return
        }
        val relay = RemoveObserverInMainThread(observer)
        observer.onSubscribe(relay)
        liveData.observeForever(relay)
    }

    private inner class RemoveObserverInMainThread(private val observer: io.reactivex.Observer<in T>)
        : MainThreadDisposable(), Observer<T> {

        override fun onChanged(t: T?) {
            if (!isDisposed) {
                if (t == null) {
                    if (valueIfNull != null) {
                        observer.onNext(valueIfNull)
                    } else {
                        observer.onError(
                            ReactiveStreamNullElementException(
                                "convert liveData value t to RxJava onNext(t), t cannot be null")
                        )
                    }
                } else {
                    observer.onNext(t)
                }
            }
        }

        override fun onDispose() {
            liveData.removeObserver(this)
        }
    }
}
`

**Comment by YvesCheung** [comment]
是的。subscribe的时候使用了liveData.observeForever，所以确实是需要dispose的。
至于是否手动，可以结合RxJava本身其他机制来使用，比如绑定RxLifecycle的生命周期，自动dispose。
